import { uniqueNamesGenerator, names, starWars } from "unique-names-generator";

// Generate squirrel names
export function grabName() {
  const funnyNicknames = [
    "Snickerdoodle",
    "Bubbles",
    "Squiggles",
    "Chuckles",
    "Gizmo",
    "Buttercup",
    "Marshmallow",
    "Giggles",
    "Sprinkles",
    "Smarty",
    "Bumblebee",
    "Sherbet",
    "Jellyfish",
    "Freckles",
    "Wiggles",
    "Fluffy",
    "Beanie",
    "Dumpling",
    "Jigsaw",
    "Gummy",
    "Sparky",
    "Squishy",
    "Pickles",
    "Scooter",
    "Ziggy",
    "Sizzle",
    "Waldo",
    "Peekaboo",
    "Goober",
    "Sunny",
    "Muffin",
    "Noodle",
    "Banana",
    "Snickers",
    "Fuzzy",
    "Jellybean",
    "Dizzy",
    "Pickle",
    "Wombat",
    "Toasty",
    "Bubblegum",
    "Flapjack",
    "Boomerang",
    "Twinkle",
    "Peaches",
    "Scooby",
    "Waffles",
    "Pudding",
    "Peanut",
    "Tater",
    "Fiddlesticks",
    "Cupcake",
    "Doodlebug",
    "Butterfingers",
    "Snuggle",
    "Bacon",
    "Sugar",
    "Ninja",
    "Moonbeam",
    "Donut",
    "Raspberry",
    "Cinnamon",
    "Kit-Kat",
    "Pumpkin",
    "Sherbet",
    "Cherry",
    "Dumpling",
    "Boomer",
    "Beanie",
    "Kitty",
    "Peppermint",
    "Cookie",
    "Tinkerbell",
    "Gummy",
    "Bubble",
    "Hiccup",
    "Ninja",
    "Squishy",
    "Cocoa",
    "Turtle",
    "Wiggly",
    "Snooze",
    "Pancake",
    "Fuzzy",
    "Sizzle",
    "Waldo",
    "Peekaboo",
    "Goober",
  ];

  const randomName = uniqueNamesGenerator({
    dictionaries: [names, funnyNicknames, starWars],
  });
  const [firstName, nickname, lastName] = randomName.split("_");
  let finalLastName = lastName.split(" " || "-");
  if (finalLastName[1]) finalLastName = finalLastName[1];
  else finalLastName = finalLastName[0];
  return `${firstName} "${nickname}" ${finalLastName}`;
}
